/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SI_lab2_167001.app;

import SI_lab2_167001.list.LinkedList;

import static SI_lab2_167001.utilities.StringUtils.join;
import static SI_lab2_167001.utilities.StringUtils.split;
import static SI_lab2_167001.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
